baseURL = "https://indigenousbiotech.com/"
languageCode = "en-us"
title = "Indigenous Biotechnology"
theme = "beautifulhugo"
publishDir = "docs"

[params]
homeTitle = "Indigenous Biotechnology"
subtitle = "Sign up to join the founding network:"
customCSS = ["css/custom.css"]

[params.contact]
email = "mctastolfi@gmail.com"
formAction = "https://formspree.io/f/mpwdrnro"  # your real Formspree link

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
